version: '3.9'

services:
  backend:
    container_name: "backend"
    build: ./backend
    networks:
      - postgres
    env_file:
      - ./backend/.env
    restart: on-failure
    ports:
      - "4000:3000"
    depends_on:
      - database

  frontend:
    container_name: "frontend"
    build: ./frontend
    restart: on-failure
    ports:
      - "8081:80"

  database:
    container_name: "postgres"
    image: "postgres:latest"
    networks:
      - postgres
    env_file:
      - ./backend/.env
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

volumes:
  pg_data:
    driver: local

networks:
  postgres:


